FROM public.ecr.aws/docker/library/python:3.13-rc-slim

# Install Tesseract
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-eng \
    && apt-get clean

COPY ./.aws /root/.aws

WORKDIR /var/task

COPY src/requirements.txt .
RUN python -m pip install -r requirements.txt

COPY src/ .

ENV PYTHONPATH=/var/task